### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by muhuashanjin** [Esri/arcgis-js-cli#44]
npm start error
## Description

D:\ArcGIS_JS\jsapi-vue-app (master -> origin) (jsapi-vue-app@1.0.0)
λ npm start

> jsapi-vue-app@1.0.0 start D:\ArcGIS_JS\jsapi-vue-app
> webpack-dev-server --history-api-fallback --mode development --open

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\ArcGIS_JS\jsapi-vue-app\node_modules\webpack-pwa-manifest\index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\ArcGIS_JS\jsapi-vue-app\webpack.config.js:10:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsapi-vue-app@1.0.0 start: `webpack-dev-server --history-api-fallback --mode development --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsapi-vue-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\administere\AppData\Roaming\npm-cache\_logs\2019-10-15T03_46_34_804Z-debug.log
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version: 版本 75.0.3770.90（正式版本） （64 位）
* Operating System and version (desktop or mobile): win10
* Link to your project if available:

**Comment by odoe** [comment]
This was something in the deps for all projects that updated due to a `^` in the package.json. It impacted all projects and I'm unsure what it was, I suspect `webpack`, `webpack-cli` or `webpack-dev-server`.

I have updated all deps across all projects and removed all use of `^` to hopefully prevent this in the future.

This should be fixed in latest release. Thanks!
