### ISSUE TITLE
generated widgets cannot be instantiated

### ISSUE THREAD

**Issue by jccartwright** [Esri/arcgis-js-cli#96]
new custom widgets scaffolded with the "widget" command line argument cannot be instantiated giving an error like:

```
ERROR in ./src/widgets/MyWidget.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/jcc/projects/arcgis-widget-test/src/widgets/MyWidget.tsx: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (20:1):
```
adding 
```
"experimentalDecorators": true
```
to the tsconfig.json does not seem to help

## Steps to Reproduce

1. arcgis create arcgis-widget-test
2. cd arcgis-widget-test
3. arcgis widget my-widget
4. in widgets.ts, modify to:
```
import LayerList from '@arcgis/core/widgets/LayerList';
import Legend from '@arcgis/core/widgets/Legend';
import MyWidget from './widgets/MyWidget';

export function initWidgets(view: __esri.MapView) {
	const legend = new Legend({ view });
	const layerList = new LayerList({ view });
	const myWidget = new MyWidget({name: 'jcc'});

	view.ui.add(legend, 'bottom-left');
	view.ui.add(layerList, 'top-right');
	view.ui.add(myWidget, 'bottom-right');
	return view;
}
```
5. npm start
Get the following error/stacktrace:
```
ERROR in ./src/widgets/MyWidget.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/jcc/projects/arcgis-widget-test/src/widgets/MyWidget.tsx: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (20:1):

  18 | };
  19 |
> 20 | @subclass('app.widgets.MyWidget')
     | ^
  21 | export default class MyWidget extends Widget {
  22 |
  23 |   @aliasOf('viewModel.view')
    at Object._raise (/Users/jcc/projects/arcgis-widget-test/node_modules/@babel/parser/lib/index.js:748:17)
    at Object.raiseWithData (/Users/jcc/projects/arcgis-widget-test/node_modules/@babel/parser/lib/index.js:741:17)
    at Object.expectOnePlugin (/Users/jcc/projects/arcgis-widget-test/node_modules/@babel/parser/lib/index.js:9116:18)
    at Object.parseDecorator (/Users/jcc/projects/arcgis-widget-test/node_modules/@babel/parser/lib/index.js:11860:10)
    at Object.parseDecorators (/Users/jcc/projects/arcgis-widget-test/node_modules/@babel/parser/lib/index.js:11842:30)
    at Object.parseStatement (/Users/jcc/projects/arcgis-widget-test/node_modules/@babel/parser/lib/index.js:11673:12)
    at Object.parseBlockOrModuleBlockBody (/Users/jcc/projects/arcgis-widget-test/node_modules/@babel/parser/lib/index.js:12258:25)
    at Object.parseBlockBody (/Users/jcc/projects/arcgis-widget-test/node_modules/@babel/parser/lib/index.js:12249:10)
    at Object.parseTopLevel (/Users/jcc/projects/arcgis-widget-test/node_modules/@babel/parser/lib/index.js:11607:10)
    at Object.parse (/Users/jcc/projects/arcgis-widget-test/node_modules/@babel/parser/lib/index.js:13415:10)
 @ ./src/widgets.ts 4:0-42 12:21-29
 @ ./src/index.ts 6:0-40 18:10-21
```
## Your Environment

* Version used: 4.18.1
* Browser Name and version: Chrome Version 87.0.4280.88 (Official Build) (x86_64)
* Operating System and version (desktop or mobile): MacOS 10.15.6
* Link to your project if available:

**Comment by koji117** [comment]
Have the exactly the same issue with the latest Firefox here. Has anybody found any workaround?

**Comment by COV-GIS** [comment]
It's a babel configuration issue. Make sure `@babel/plugin-proposal-class-properties`and `@babel/plugin-proposal-decorators` packages are installed, and babel config plugins are configured like...

```json
"plugins": [
  [
    "@babel/plugin-proposal-decorators",
    {
      "legacy": true
    }
  ],
  [
    "@babel/plugin-proposal-class-properties",
    {
      "loose": true
    }
  ]
]
```

`@babel/plugin-proposal-decorators` needs to be the first babel plugin if you are using other plugins.

**Comment by koji117** [comment]
After trying the above solution, I faced the error below. 
` 'import =' is not supported by @babel/plugin-transform-typescript`

So I commented out `import esri = __esri` and replaced all `__esri` with  `esri`. 
Then I get the following error now. 
```
Module parse failed: Unexpected token (65:13)
File was processed with these loaders:`
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
```
Would you able to suggest any workaround at this point?

**Comment by nikator** [comment]
I not sure if it can be resolved with babel configuration. But workaround would be to replace `babel-loader` to `ts-loader` in `webpack.config.js`:
```
...
    module: {  
      rules: [  
        {  
          test: /\.(ts|js)x?$/,  
          exclude: /node_modules/,  
          loader: 'ts-loader'  
        },  
...
```

**Comment by odoe** [comment]
A recent PR was merged that might fix this. I'll get a new patch release with it out by end of week.
